version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  flask_app:
    build: .
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      FLASK_SECRET: "flask_secret key"
      FLASK_ENV: development

      AWS_ACCESS_KEY: "aws_access_key"
      AWS_SECRET_KEY: "aws_secret_key"
      S3_BUCKET_NAME: "s3_bucket_name"

      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST: "postgres"
      POSTGRES_DB: "mydb"

    links:
      - postgres

volumes:
  postgres_data:
